apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-creds-rotate
  namespace: ecr-creds-rotate

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ecr-creds-rotate-role
rules:
- apiGroups:
  - '*'
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - serviceaccounts
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ecr-creds-rotate-binding
subjects:
- kind: ServiceAccount
  name: ecr-creds-rotate
  namespace: ecr-creds-rotate
roleRef:
  kind: ClusterRole
  name: ecr-creds-rotate-role
  apiGroup: rbac.authorization.k8s.io

---