apiVersion: v1
kind: Secret
metadata:
  name: ecr-creds-rotate
  namespace: ecr-creds-rotate
type: Opaque
stringData:
  ECR_REGISTRY: "<private-ecr-registry>"
  REGION: "<aws-region>"
  ACCESS_KEY_ID: "<access-key>"
  SECRET_ACCESS_KEY: "<secret-access-key>"

---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: ecr-creds-rotate
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: "<initial-dockerconfig-from-aws-ecr-cli>"